services:
  redis:
    image: redis:alpine
    restart: always

  weather:
    image: ghcr.io/cryzz2/weather-pyapp:latest
    build: .
    depends_on:
      - redis
    restart: always
    ports:
      - "80:80"
